"""
Vocabulary definitions for dataset generation.
"""

# Star Wars themed vocabulary
STAR_WARS_VOCABULARY = [
    # ===== TERMS & CONCEPTS =====
    "JEDI", "SITH", "FORCE", "LIGHTSABER", "DARKSIDE", "LIGHTSIDE", "MIDICHLORIANS",
    "PADAWAN", "KNIGHT", "MASTER", "COUNCIL", "TEMPLE", "YOUNGLING", "INQUISITOR",
    "INQUISITORIUS", "MANDALORIAN", "BOUNTYHUNTER", "SMUGGLER", "SCAVENGER",
    "CLONE", "DROID", "ASTROMECH", "PROTOCOLDROID", "BATTLEDROID",
    "HOLOCRON", "HOLOPROJECTOR", "HOLONET",
    "HYPERSPACE", "HYPERDRIVE", "LIGHTSPEED", "PARSEC",
    "KYBER", "BESKAR", "CARBONITE",
    "REBEL", "IMPERIAL", "ALLIANCE", "REPUBLIC", "NEWREPUBLIC",
    "FIRSTORDER", "RESISTANCE", "SEPARATIST",
    "WAR", "BATTLE", "AMBUSH", "BLOCKADE",
    "SENATE", "SENATOR", "EMPEROR", "CHANCELLOR", "MOFF",
    "NIGHTSISTER", "NIGHTBROTHER",
    # Astronomy (general sci-fi useful)
    "GALAXY", "STAR", "PLANET", "MOON", "NEBULA", "SUPERNOVA", "QUASAR", "PULSAR",
    "ASTEROID", "METEOR", "METEORITE", "COMET", "ORBIT", "GRAVITY", "COSMOS", "STARFIELD",

    # ===== FACTIONS & ORGS =====
    "GALACTICEMPIRE", "GALACTICREPUBLIC", "JEDIORDER", "SITHORDER",
    "REBELLION", "RESISTANCE", "FIRSTORDER", "CONFEDERACY", "TRADEFEDERATION",
    "TECHNOUNION", "BLACKSUN", "CRIMESYNDICATE", "PYKESYNDICATE",

    # ===== PLANETS & LOCATIONS =====
    # Films (saga + stories)
    "TATOOINE", "CORUSCANT", "NABOO", "ALDERAAN", "HOTH", "DAGOBAH", "BESPIN", "ENDOR",
    "YAVIN4", "JAKKU", "STARKILLERBASE", "AHCHTO", "CRAIT", "EXEGOL", "PASAANA",
    "KIJIMI", "KEFBIR", "SCARIF", "JEDHA", "EADU", "LAHMU", "WOBANI", "CORELLIA",
    "MUSTAFAR", "GEONOSIS", "KAMINO", "UTAPAU", "KASHYYYK", "SULLUST", "DANTOOINE",
    "POLISMASSA", "TAKODANA",
    # TV (Mandalorian / Ahsoka / Andor / Rebels / Clone Wars / Bad Batch など)
    "NEVARRO", "ARVALA7", "SORGAN", "TRASK", "MORAK", "TYTHON",
    "SEATOS", "PERIDEA",
    "FERRIX", "MORLANAONE", "NARKINA5", "KENARI", "NIAMOS", "ERIADU",
    "MANDALORE", "CONCORDIA", "CONCORDDAWN", "KROWNEST",
    "LIRA SAN",  # keep as one token w/o space
    "LIRASAN",
    "ATOLLON", "MALACHOR", "DATHOMIR", "RYLOTH", "RISHI", "FELUCIA",
    "UMBARA", "CHRISTOPHSIS", "SALEUCAMI", "MORTIS", "ZYGERRIA",
    "ILUM", "MORABAND", "KORRIBAN", "SERENNO", "SCIPIO", "CATONEIMOIDIA", "MYGEETO",
    "SEELOS", "TETH", "TOYDARIA", "DEVARON", "ONDERON", "FLORRUM", "IEGO", "RAXUS",
    "PANTORA", "BRACCA", "DARO", "ORDMANTELL", "ANAXES", "JABIIM", "CHANDRILA",
    # Parks (Star Tours / Galaxy’s Edge)
    "BATUU", "BLACKSPIREOUTPOST", "HALCYON",

    # ===== SHIPS & VEHICLES =====
    "MILLENNIUMFALCON", "FALCON",
    "XWING", "YWING", "AWING", "BWING", "UWING", "N1STARFIGHTER", "ARC170", "Z95",
    "TIEFIGHTER", "TIEINTERCEPTOR", "TIEBOMBER", "TIEDEFENDER", "TIESILENCER",
    "STARDESTROYER", "SUPERSTARDESTROYER", "VENATOR", "ACCLAMATOR", "ARQUITENS",
    "IMPERIALSHUTTLE", "LAMBDASHUTTLE", "SENTINELSHUTTLE",
    "DEATHSTAR", "DEATHSTARII",
    "STARFIGHTER", "CRUISER", "FRIGATE", "CORVETTE",
    "SNOWSPEEDER", "LANDSPEEDER", "SPEEDERBIKE", "PODRACER", "LAAT",
    "DROIDTRIFIGHTER", "VULTUREDROID", "GAUNTLETSTARFIGHTER",
    # Tech / weapons
    "BLASTER", "BOWCASTER", "DARKSABER", "SHIELD", "DEFLECTOR", "TRACTORBEAM", "REACTOR",

    # ===== CHARACTERS =====
    # Original Trilogy / Prequels / Sequels
    "LUKESKYWALKER", "LEIAORGANA", "HANSOLO", "CHEWBACCA", "OBIWANKENOBI", "YODA",
    "ANAKINSKYWALKER", "PADMEAMIDALA", "QUIGONJINN", "MACEWINDU",
    "DARTHVADER", "PALPATINE", "DARTHSIDIOUS", "DARTHMAUL", "COUNTDOOKU", "GRIEVOUS",
    "LANDOCALRISSIAN", "WEDGEANTILLES", "MONMOTHMA", "TARKIN", "ACKBAR",
    "R2D2", "C3PO", "BB8", "K2SO",
    "REY", "FINN", "POEDAMERON", "KYLOREN", "SNOKE", "PHASMA", "HUX",
    # Story films
    "JYNERSO", "CASSIANANDOR", "SAWGERRERA", "GALENER SO",
    # Mandalorian / Ahsoka / Rebels / Andor / Bad Batch
    "DINDJARIN", "GROGU", "MOFFGIDEON", "BOKATAN", "KUIIL", "GREEF KARGA",
    "AHSOKA", "SABINEWREN", "EZRABRIDGER", "HERASYNDULLA", "CHOPPER", "THRAWN",
    "CROSSHAIR", "HUNTER", "WRECKER", "TECH", "OMEGA",
    # Bounty hunters & others
    "JANGOFETT", "BOBAFETT", "CADBANE", "AURRA SING", "ASAJJVENTRESS",
    "HONDOOHNAKA", "ENFYSNEST",

    # ===== SPECIES =====
    "WOOKIEE", "HUMAN", "TWILEK", "TWI LEK",  # alternative token (optional)
    "ZABRAK", "KELDOR", "MIRIALAN", "MIRALUKA",
    "TOGRUTA", "RODIAN", "ITHORIAN", "DUROS", "BITH", "TALZ", "KUBAZ",
    "SULLUSTAN", "BOTHAN", "DEVARONIAN", "MONCALAMARI", "QUARREN",
    "TRANDOSHAN", "GAMORREAN", "NIKTO", "ARCONA", "TOYDARIAN", "JAWA", "EWOK",
    "GUNGAN", "HUTT", "CHISS", "ZYGERRIAN", "TUSKENRAIDER",
]