# SynthTIGER configuration fragment for Aurebesh dataset generation
style:
  font:
    # Font sampling probabilities
    core_prob: 0.7
    variant_prob: 0.3
    fancy_prob: 0.0
  
  # Text generation parameters
  text:
    min_words: 1
    max_words: 5
    min_word_length: 2
    max_word_length: 10
    
  # Layout parameters
  layout:
    spacing_range: [0.8, 1.2]
    line_spacing_range: [0.9, 1.1]
    min_text_spacing: 30  # Minimum pixels between text blocks (reduced for more blocks)
    max_text_blocks: 10   # Maximum number of text blocks per image
    adaptive_spacing: true  # Enable adaptive spacing based on number of blocks
    
  # Color parameters
  color:
    text_color_mode: "random"  # random, fixed
    background_mode: "mixed"    # image, synthetic, mixed
    synthetic_bg_prob: 0.2
    
  # Effects
  effects:
    shadow_prob: 0.3
    border_prob: 0.2
    rotation_prob: 0.2
    rotation_range: [-5, 5]
    
# Augmentation parameters
augmentation:
  perspective:
    prob: 0.3
    degree_range: [-10, 10]
    
  noise:
    prob: 0.3
    var_range: [0.001, 0.005]

  blur:
    prob: 0.3
    kernel_range: [1, 3]
    
  jpeg:
    prob: 0.5
    quality_range: [70, 95]