# SynthTIGER configuration fragment for Aurebesh dataset generation

# Text generation distribution
text_generation:
  wordfreq_limit: 10000          # Top N words from wordfreq to use
  random_text_ratio: 0.05        # 5% random text for robustness
  numeric_text_ratio: 0.15       # 15% numeric/mixed content for number recognition
  # Remaining: 80% vocabulary text (wordfreq + Star Wars)

style:
  font:
    # Font sampling probabilities
    core_prob: 0.7
    variant_prob: 0.3
  
  # Text generation parameters
  text:
    min_words: 1
    max_words: 5
    min_word_length: 2
    max_word_length: 10
    
  # Layout parameters
  layout:
    spacing_range: [0.8, 1.2]
    line_spacing_range: [0.9, 1.1]
    min_text_spacing: 30  # Minimum pixels between text blocks (reduced for more blocks)
    max_text_blocks: 10   # Maximum number of text blocks per image
    adaptive_spacing: true  # Enable adaptive spacing based on number of blocks
    
  # Text variants
  variants:
    multiline_prob: 0.3     # Probability of multi-line text (2-3 lines)
    size_contrast_prob: 0.2 # Probability of size contrast text (2x size difference)
    
  # Color parameters
  color:
    text_color_mode: "random"  # random, fixed
    background_mode: "mixed"    # image, synthetic, mixed
    synthetic_bg_prob: 0.5    # 50% synthetic backgrounds
    
    # Synthetic background pattern probabilities (must sum to 1.0)
    synthetic_patterns:
      solid_color: 0.2        # 20% of synthetic = 10% total
      gradient: 0.2           # 20% of synthetic = 10% total
      random_lines: 0.2       # 20% of synthetic = 10% total
      geometric_shapes: 0.16  # 16% of synthetic = 8% total
      noise_texture: 0.14     # 14% of synthetic = 7% total
      pseudo_characters: 0.1  # 10% of synthetic = 5% total
    
  # Effects
  effects:
    shadow_prob: 0.3
    border_prob: 0.2
    rotation_prob: 0.2
    rotation_range: [-5, 5]
    
# Augmentation parameters
augmentation:
  perspective:
    prob: 0.3
    degree_range: [-10, 10]
    
  noise:
    prob: 0.3
    var_range: [0.001, 0.005]

  blur:
    prob: 0.3
    kernel_range: [1, 3]
    
  jpeg:
    prob: 0.5
    quality_range: [70, 95]