detector:
  # DBPostProcessor のしきい値
  bin_thresh: 0.35
  box_thresh: 0.68
  unclip_ratio: 1.3
  min_size: 3

  # 評価時のマッチング閾値
  iou_thresh: 0.5

recognizer:
  # デコード方式
  beam_width: 1  # 1=greedy, 5〜10=beam search

  # 後段フィルタ
  min_conf: 0.60
  # min_len: 2  # min_confで十分な場合が多いが、それでも誤認識が多い場合に使用
