detector:
  # DBPostProcessor のしきい値
  bin_thresh: 0.35
  box_thresh: 0.68
  unclip_ratio: 1.3

  # 評価時のマッチング閾値
  iou_thresh: 0.5

recognizer:
  # 後段フィルタ
  min_conf: 0.60   # 信頼度が低い検出結果を除外
  # min_len: 2       # 短すぎるテキストを除外（文字数）。min_confで十分な場合が多いが、それでも誤認識が多い場合に使用
