epochs: 40
batch_size: 64
optimizer:
  name: AdamW
  lr: 2.0e-4
  weight_decay: 1.0e-4
scheduler:
  name: OneCycleLR
  pct_start: 0.3         # 30 % warm-up
  max_lr: 2.0e-4
metrics: [cer]
charset: charset_aurebesh.yaml